server:
  port: 8091

spring:
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  data:
    web:
      pageable:
        default-page-size: 12
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: jin
      password: 1234
      database: sections
      uri: mongodb://localhost:27017/sections

  datasource:
    initialize-schema: always
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/batch?serverTimezone=Asia/Seoul
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
  kafka:
    bootstrap-servers: 172.18.0.101:9092
    consumer:
      auto-offset-reset: earliest


#eureka:
#  instance:
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://43.200.189.164:8761/eureka

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
    com:
      readme:
        batch=DEBUG:
    root=DEBUG: